-- DROP DATABASE IF EXISTS exampledb;
-- CREATE DATABASE exampledb;

-- DROP DATABASE IF EXISTS testdb;
-- CREATE DATABASE testdb;


DROP DATABASE IF EXISTS fithub_db;
CREATE DATABASE fithub_db;

CREATE TABlE profile(
    id INTEGER(100) AUTO_INCREMENT NOT NULL,
    name VARCHAR (100) NOT NULL,
    gender VARCHAR (10) NOT NULL,
    age INTEGER(10) NOT NULL,
    weight DECIMAL(10) NOT NULL,
    height DECIMAL(10) NOT NULL,
    PRIMARY KEY(id)
);
